spring:
  application:
    name: "project_manager"
  datasource:
    url: jdbc:mysql://192.168.0.1:8090/test?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: DZ5NLmSWkpFvMJ5
    driver-class-name: com.mysql.cj.jdbc.Driver

    hikari:
      minimum-idle: 10
      maximum-pool-size: 100
      auto-commit: true
      idle-timeout: 600
      max-lifetime: 180000
      connection-timeout: 30000

  jackson:
    property-naming-strategy: SNAKE_CASE

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  port: 9001

file:
  base:
    url: http://localhost:9001/file
  root:
    path: /Users/bileskou/Documents/zky/project_manager/file/
