spring:
  application:
    name: "project_manager"
  datasource:
    url: jdbc:mysql://192.168.1.111:3306/project_manager?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: project
    password: project
    driver-class-name: com.mysql.cj.jdbc.Driver

    hikari:
      minimum-idle: 10
      maximum-pool-size: 100
      auto-commit: true
      idle-timeout: 600
      max-lifetime: 180000
      connection-timeout: 30000
  data:
    redis:
      host: 192.168.1.111
      port: 6379
      password: Qwer123!@#
      timeout: 5000ms # 连接超时时间
      lettuce:
        pool:
          max-active: 8 # 连接池最大连接数
          max-idle: 8   # 连接池最大空闲连接数
          min-idle: 0   # 连接池最小空闲连接数
          max-wait: -1  # 连接池最大阻塞等待时间（-1表示无限制）

  jackson:
    property-naming-strategy: SNAKE_CASE

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

mybatis-plus:
  mapper-locations: classpath*:mappers/**/*.xml
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  port: 9001

file:
  base:
    url: http://localhost:9001/file
  old:
    plan: C:\Users\biles\Documents\Works\Zky\projectmanagerapi\file\old_drawing_plan
  root:
    path: C:\Users\biles\Documents\Works\Zky\projectmanagerapi\file

debug: true
logging:
  level:
    org.springframework.boot: debug
    com.zkyzn.project_manager.crons.DelayNoticeCron: debug # 新增这一行，用于调试定时任务
    com.zkyzn.project_manager.crons.WeeklyReportCron: debug
    org.springframework.scheduling.annotation.ScheduledAnnotationBeanPostProcessor: debug # 用于查看定时任务的调度信息
security:
  jwt:
    enabled: false

